// Generated by scripts/generate-brainpet-adapter-contracts.mjs. Do not edit.
export const agentActivitySchemaVersion = 1 as const;
export const agentActivityMethod = "agent.activity" as const;
export const normalizedAgentLifecycleStates = ["working","waiting","ready","blocked","idle"] as const;
export const agentActivityRequiredFields = ["schemaVersion","agent","sessionId","state","occurredAt","capabilities"] as const;
export const agentActivityOptionalFields = ["turnId","request"] as const;
export const agentActivityPrivacyRejectedFields = ["prompt","transcript","cwd","toolInput","toolOutput","response"] as const;
