// Generated by scripts/generate-brainpet-adapter-contracts.mjs. Do not edit.
pub const ADAPTER_VERSION: &str = "1.0.0";
pub const AGENT_ACTIVITY_SCHEMA_VERSION: u64 = 1;
pub const AGENT_ACTIVITY_METHOD: &str = "agent.activity";
pub const LIFECYCLE_STATES: &[&str] = &["working", "waiting", "ready", "blocked", "idle"];
pub const PRIVACY_REJECTED_FIELDS: &[&str] = &[
    "prompt",
    "transcript",
    "cwd",
    "toolInput",
    "toolOutput",
    "response",
];
pub const IPC_PROTOCOL: &str = "openpets-ipc";
pub const IPC_PROTOCOL_VERSION: u64 = 1;
pub const MAX_IPC_MESSAGE_BYTES: usize = 16384;
pub const HOOK_DEADLINE_MS: u64 = 2600;
pub const CONNECT_ATTEMPT_MS: u64 = 350;
pub const RUNTIME_POLL_INTERVAL_MS: u64 = 50;
pub const BRAINPET_APP_ID: &str = "dev.brainpet.app";
pub const BRAINPET_PRODUCT_DIRECTORY: &str = "BrainPet";
pub const BRAINPET_RUNTIME_NAMESPACE: &str = "brainpet";
