// Generated by scripts/generate-brainpet-adapter-contracts.mjs. Do not edit.
export const brainPetBridgeVersion = "0.3.0" as const;
export const brainPetReleaseTargets = [
  {
    "id": "windows-x64",
    "platform": "windows",
    "nodePlatform": "win32",
    "electronPlatform": "win",
    "arch": "x64",
    "rustTarget": "x86_64-pc-windows-msvc",
    "helperName": "brainpet-hook.exe",
    "binaryFormat": "pe",
    "machine": 34404,
    "supportLevel": "stable"
  },
  {
    "id": "windows-arm64",
    "platform": "windows",
    "nodePlatform": "win32",
    "electronPlatform": "win",
    "arch": "arm64",
    "rustTarget": "aarch64-pc-windows-msvc",
    "helperName": "brainpet-hook.exe",
    "binaryFormat": "pe",
    "machine": 43620,
    "supportLevel": "preview"
  },
  {
    "id": "macos-x64",
    "platform": "macos",
    "nodePlatform": "darwin",
    "electronPlatform": "mac",
    "arch": "x64",
    "rustTarget": "x86_64-apple-darwin",
    "helperName": "brainpet-hook",
    "binaryFormat": "mach-o",
    "machine": 16777223,
    "supportLevel": "beta"
  },
  {
    "id": "macos-arm64",
    "platform": "macos",
    "nodePlatform": "darwin",
    "electronPlatform": "mac",
    "arch": "arm64",
    "rustTarget": "aarch64-apple-darwin",
    "helperName": "brainpet-hook",
    "binaryFormat": "mach-o",
    "machine": 16777228,
    "supportLevel": "stable"
  },
  {
    "id": "linux-x64",
    "platform": "linux",
    "nodePlatform": "linux",
    "electronPlatform": "linux",
    "arch": "x64",
    "rustTarget": "x86_64-unknown-linux-gnu",
    "helperName": "brainpet-hook",
    "binaryFormat": "elf",
    "machine": 62,
    "supportLevel": "beta"
  },
  {
    "id": "linux-arm64",
    "platform": "linux",
    "nodePlatform": "linux",
    "electronPlatform": "linux",
    "arch": "arm64",
    "rustTarget": "aarch64-unknown-linux-gnu",
    "helperName": "brainpet-hook",
    "binaryFormat": "elf",
    "machine": 183,
    "supportLevel": "preview"
  }
] as const;
export const brainPetDistributionIdentity = {
  "profile": "brainpet",
  "displayName": "BrainPet",
  "appId": "dev.brainpet.app",
  "executableName": "brainpet",
  "repository": "hmhm2333/brainpet",
  "updateRepository": "hmhm2333/brainpet"
} as const;
