// Generated by scripts/generate-brainpet-adapter-contracts.mjs. Do not edit.
export const adapterContractVersion = "1.0.0" as const;
export const targetProductDefinitions = {
  "brainpet": {
    "appId": "dev.brainpet.app",
    "productDirectory": "BrainPet",
    "runtimeNamespace": "brainpet",
    "updateChannel": "hmhm2333/brainpet"
  },
  "openpets": {
    "appId": "dev.openpets.app",
    "productDirectory": "OpenPets",
    "runtimeNamespace": "openpets",
    "updateChannel": "alvinunreal/openpets"
  }
} as const;
